### ISSUE TITLE
Support detection of triplet targets for Rust projects

### ISSUE THREAD

**Issue by viccuad** [opensbom-generator/spdx-sbom-generator#274]
## Summary

For Rust, support detection of cross-compilation and list the system libraries used (glibc, musl, linker, compiler, etc).

This may mean [supporting `.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html).

This file has sections of `[target.<triple>]`. These sections specify settings for [specific platform targets](https://doc.rust-lang.org/beta/rustc/platform-support.html),  [see the config.toml docs.](https://doc.rust-lang.org/cargo/reference/config.html#target). These triplets can be used to compile against a different system library (musl instead of glibc for example), different machine architecture, etc, as usual. Example:

```toml
# .cargo/config.toml

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
```

Note that key options for those sections can be also overridden via env vars. Maybe there's a way to call `cargo` to obtain the end evaluation that takes into account the env vars. 

## Background

Right now, SBOM of a rust project compiled for amd64 and glibc is basically the same as if compiled for arm64 and musl. Instead, this information should be included in the SBOM.
